# Generated by Django 5.0.2 on 2024-02-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_alter_videoresponse_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoresponse',
            name='user_id',
        ),
        migrations.AddField(
            model_name='videoresponse',
            name='matricule',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
